### ISSUE TITLE
Why do I need a loader?

### ISSUE THREAD

**Issue by iamryuzaki** [mesilov/bitrix24-php-sdk#110]
What kind of imprinted this project, this is the only normal solution, but the author managed to write it with his claws and spoil the idea! I have a project without a loader (autoloader) - and your code without autoloader is not possible to use! As you only Team Lead hands are not torn off ....

**Comment by DarkRiDDeR** [comment]
Why is the autoloader bad? This is a common and convenient approach

**Comment by mesilov** [comment]
@iamryuzaki plz, use composer

http://www.phptherightway.com/#composer_and_packagist
