### ISSUE TITLE
Генерация лида

### ISSUE THREAD

**Issue by dormadekhin-denis** [mesilov/bitrix24-php-sdk#115]
Добрый день! возможно ли использовать вашу библиотеку для генерации лида? если да можно ли увидеть пример?

**Comment by mesilov** [comment]
https://dev.1c-bitrix.ru/rest_help/crm/leads/crm_lead_add.php

**Comment by catthecreator** [comment]
Ответ из разряда "напишите свою обертку"?) Сабж просит показать пример использования в вашей библиотеке, а не тыкнуть его носом в документацию
