### ISSUE TITLE
How to upload PHOTO in contact?

### ISSUE THREAD

**Issue by ravindersinghdang** [mesilov/bitrix24-php-sdk#123]
Hello,

I m trying to update contact profile photo but no luck. Profile info is getting updated and i m not getting any error but the profile PHOTO is not updating. Here is the array i m sending:

`(
    [PHOTO] => Array
        (
            [fileData] => Array
                (
                    [name] => test.jpg
                    [type] => image/jpeg
                    [tmp_name] => /tmp/phpQxj6JR
                    [error] => 0
                    [size] => 130991
                )
        )
    [NAME] => test
    [OPENED] => Y
    [ASSIGNED_BY_ID] => 1
    [TYPE_ID] => CLIENT
    [SOURCE_ID] => SELF
    [SECOND_NAME] => test
    [LAST_NAME] => test
    [BIRTHDATE] => 06/22/1990
    [SOURCE_DESCRIPTION] => testing description
    [ADDRESS] => test
    [ADDRESS_CITY] => test
    [ADDRESS_POSTAL_CODE] => 123456
    [ADDRESS_COUNTRY_CODE] => 91
    [UF_CRM_1537794576302] => 
    [COMMENTS] => testing comment
    [PHONE] => 123123123
    [WEB] => www.test.com
)`

This is the response i m getting:

`Array
(
    [result] => 1
    [time] => Array
        (
            [start] => 1538221895.9551
            [finish] => 1538221896.0858
            [duration] => 0.1306791305542
            [processing] => 0.085424900054932
            [date_start] => 2018-09-29T14:51:35+03:00
            [date_finish] => 2018-09-29T14:51:36+03:00
        )
)`

I tried many ways but still no luck.

Can anyone please help me here?

**Comment by OAPrilepa** [comment]
Try use key 'PERSONAL_PHOTO'
https://dev.1c-bitrix.ru/rest_help/users/user_fields.php
