### ISSUE TITLE
Где взять значения для функций setMemberId, setAccessToken, setRefreshToken?

### ISSUE THREAD

**Issue by fomvasss** [mesilov/bitrix24-php-sdk#134]
В примере документации этого пакета есть код:
```php
$obB24App->setMemberId($arParams['MEMBER_ID']);
$obB24App->setAccessToken($arParams['AUTH_ID']);
$obB24App->setRefreshToken($arParams['REFRESH_ID']);
```
Пока что мне совсем не понятно, где взять значения для функций: setMemberId, setAccessToken, setRefreshToken... 
Возможно где то, есть пример, как вообще авторизоватся и передать данные в Bitrix24? Заранее спасибо за ответы!

**Comment by xUJYx** [comment]
setMemberId - member ID - это ID пользователя из битрикса http://dl3.joxi.net/drive/2019/04/14/0000/1681/22161/61/f06cf47657.jpg
Access_token и RefreshToken - это краеугольный камень, который сложно достать (по крайней мере мне было сложно достать). Самое простое - воспользоваться [моей библиотечкой для получения этих токенов авторизации](https://github.com/xUJYx/bitrix24_api_authorization/blob/master/README.ru.md) . Собственно я дал ссылку на РУ доку библиотечки, если будут вопросы - задавай в [ISSUE](https://github.com/xUJYx/bitrix24_api_authorization/issues) библиотеки...

**Comment by fomvasss** [comment]
Спасибо за ответ! Уже решил этот вопрос другим путем - создал [небольшой пакет](https://github.com/fomvasss/bitrix24-api-hook) для работы с Bitrix24 через его веб-хуки. Работает отлично, поддерживается весь функционал API, да и с авторизацией нет не каких проблем. Единственное, что возможно не так безопасно, но главное что бы никто лишний не получил ссылку на веб-хук.

**Comment by xUJYx** [comment]
> Спасибо за ответ!
> Уже решил этот вопрос другим путем - создал [небольшой пакет](https://github.com/fomvasss/bitrix24-api-hook) для работы с Bitrix24 через его веб-хуки. Работает отлично, поддерживается весь функционал API, да и с авторизацией нет не каких проблем.
> Единственное, что возможно не так безопасно, но главное что бы никто лишний не получил ссылку на веб-хук.

Это да, видел библиотечку для работы через вебхуки. Просто подумал, что если у Вас проект уже написан для работы через текущую библиотеку - могут быть сложности в переходе...

Если вопрос решен - закройте этот ISSUE ;)

**Comment by fomvasss** [comment]
> Это да, видел библиотечку для работы через вебхуки. Просто подумал, что если у Вас проект уже написан для работы через текущую библиотеку - могут быть сложности в переходе...

Я что-то не видел, возможно у вас есть ссылка? хотел бы взглянуть на ее реализацию....

**Comment by xUJYx** [comment]
> Я что-то не видел, возможно у вас есть ссылка

Я имел в виду у Вас в репозитории )

А по-хорошему, можно было бы и текущую библиотеку адаптировать. По-большому счёту разницы в отправке запросов нет - отличие лишь в адресе по которому отправляется запрос...
Нужно будет как-нибудь на досуге подумать над реализацией...

**Comment by fomvasss** [comment]
Ну реализация текущей библиотеки отличается от моей не только лишь в адресе по которому отправляется запрос :) Как [видно](https://github.com/fomvasss/bitrix24-api-hook/blob/master/src/Bitrix24.php) у меня только один не большой класс, в котором все реализовано)

**Comment by xUJYx** [comment]
> Ну реализация текущей библиотеки отличается от моей не только лишь в адресе по которому отправляется запрос :)

Я говорил о разнице в самой работе. Думаю если изменить адрес отправки данных - текущая библиотека отлично продолжить работать, только уже с вебхуками...
