### ISSUE TITLE
Именование классов согласно расположению в папках

### ISSUE THREAD

**Issue by Sellec** [mesilov/bitrix24-php-sdk#142]
Согласуйте пространства имен и расположение файлов классов в папках. Невозможно использовать autoloader по namespace, так как расположение классов неочевидно.

**Comment by viktor-melnikov** [comment]
у меня все корректно работает :) laravel 5.8

**Comment by dasauser** [comment]
да, тоже все ок (symfony 4)

**Comment by mesilov** [comment]
see 2.x version
