### ISSUE TITLE
chain calls in credentials

### ISSUE THREAD

**Issue by viktor-melnikov** [mesilov/bitrix24-php-sdk#143]
Сделайте нормальный возврат объекта из методов `return $this;`. Можно будет делать нормальную цепочку  #вызовов

`$obB24App = new \Bitrix24\Bitrix24(false, $log);
$obB24App->setApplicationScope($arParams['B24_APPLICATION_SCOPE']);
$obB24App->setApplicationId($arParams['B24_APPLICATION_ID']);
$obB24App->setApplicationSecret($arParams['B24_APPLICATION_SECRET']);`

**Comment by mesilov** [comment]
see 2.x credentials
