### ISSUE TITLE
Поддержка 

### ISSUE THREAD

**Issue by outZoNe** [mesilov/bitrix24-php-sdk#150]
Здравствуйте, тут: https://dev.1c-bitrix.ru/rest_help/tasks/task/item/list.php сказано, что "Метод устарел и не поддерживается". Будет ли обновление?

**Comment by mesilov** [comment]
пожалуйста, реализуйте самостоятельно методы https://dev.1c-bitrix.ru/rest_help/tasks/task/tasks/index.php и сделайте PR
