### ISSUE TITLE
Вопрос про удаление сущностей

### ISSUE THREAD

**Issue by Vadimushka** [mesilov/bitrix24-php-sdk#151]
Если выполняется команда https://dev.1c-bitrix.ru/rest_help/crm/cdeals/crm_deal_delete.php

что происходит со сделкой? - она перемещается в корзину? или полностью удаляется? это вопрос не ясен!

**Comment by maxyc** [comment]
это явно вопрос тех поддержке битрикса, а не тут.

**Comment by Vadimushka** [comment]
Понятно
