### ISSUE TITLE
не вижу причин не добавить авторизацию в пакет

### ISSUE THREAD

**Issue by maxyc** [mesilov/bitrix24-php-sdk#158]
в чем сложность? сейчас требуется делать абстракции только лишь для авторизации

**Comment by xsen** [comment]
@maxyc возможно вы сможете это сделать сами и отправить PR?

**Comment by xUJYx** [comment]
@xsen Можете воспользоваться моей библиотечкой. Учитывая то, как принимаются PR - реализации можно ждать долго...
