### ISSUE TITLE
Add getById() method to User class

### ISSUE THREAD

**Issue by waleev** [mesilov/bitrix24-php-sdk#174]
Метод API `user.get` предполагает также и такой вызов:
`BX24.callMethod('user.get', {"ID": 1});`
Нужно добавить для этого случая отдельный метод.

https://dev.1c-bitrix.ru/rest_help/users/user_get.php

**Comment by mesilov** [comment]
добавьте пожалуйста в ветку 1.x

**Comment by waleev** [comment]
#184
