### ISSUE TITLE
Installation problems with 2.x version

### ISSUE THREAD

**Issue by waleev** [mesilov/bitrix24-php-sdk#199]
According to instruction in README:
> Add "mesilov/bitrix24-php-sdk": "2.x" to composer.json of your application.

But after this we have a problem:

> Problem 1
>  - Root composer.json requires mesilov/bitrix24-php-sdk 2.x, found mesilov/bitrix24-php-sdk[2.x-dev] but it does not match your minimum-stability.

This problem can be resolved by changing minimum stability to dev. OK.

But we have another one:
> - mesilov/bitrix24-php-sdk 2.x-dev requires symfony/http-client-contracts 5.2.* -> found symfony/http-client-contracts[dev-master, dev-main, v1.1.1, ..., v1.1.10, v2.0.0, ..., 2.3.x-dev (alias of dev-master)] but it does not match the constraint.

Reason is in this line:
https://github.com/mesilov/bitrix24-php-sdk/blob/2156a97f1552ec53d70772f5ebb7af3f3437f9f3/composer.json#L26

There is no such version.
What's the solution?

**Comment by mesilov** [comment]
@waleev thanks
