### ISSUE TITLE
Add a support a method batch in base class

### ISSUE THREAD

**Issue by mesilov** [mesilov/bitrix24-php-sdk#2]
http://dev.1c-bitrix.ru/rest_help/general/batch.php

**Comment by drumrock** [comment]
This can be implemented as 3 methods and delayed execution:

//Start batch block
$obApp->batchStart();
//API-calls to be packed into batch
$obLead->getList();
$obLead->get();
...
//Batch end
$obApp->batchEnd();
//Run batch
$obApp->batchExecute();

Every method called for the same $obApp between $obApp->batchStart() 
and $obApp->batchEnd() has to be stored in some cache ($batch[] = methodName+paramsArray),
but not executed immediately. And the all these stored methods
have to be executed on $obApp->batchExecute();

Programming effort here can be minimized by changing Bitrix24::call() 
to support delayed API-calls execution.

All other methods can be left untouched.

**Comment by maranqz** [comment]
Will it be implemented in the near future?
