### ISSUE TITLE
Need update minimal php versoin in README

### ISSUE THREAD

**Issue by DarkTraveler** [mesilov/bitrix24-php-sdk#211]
![image](https://user-images.githubusercontent.com/16899697/107590721-9a7f0380-6c54-11eb-949a-0b66a2c79fbc.png)

![image](https://user-images.githubusercontent.com/16899697/107590737-a79bf280-6c54-11eb-95aa-97294f7b22aa.png)

Minimal version now 7.4

**Comment by mesilov** [comment]
fixed https://github.com/mesilov/bitrix24-php-sdk/blob/master/composer.json#L20
