### ISSUE TITLE
_onCallApiMothod != _onCallApiMethod

### ISSUE THREAD

**Issue by DirsPrihodko** [mesilov/bitrix24-php-sdk#219]

**Comment by mesilov** [comment]
@DirsPrihodko can you describe problems?

**Comment by DirsPrihodko** [comment]
@mesilov 
You define var
    /**
     * @var callable callback after api method called
     */
    protected $_onCallApiMethod;

But use _onCallApiMothod :
public function setOnCallApiMethod(callable $callback)
    {
        $this->_onCallApiMothod = $callback;
    }
....
if (is_callable($this->_onCallApiMothod)) {
                call_user_func($this->_onCallApiMothod, $this, $methodName);
            }

**Comment by camaxtly** [comment]
fixed #220
