### ISSUE TITLE
Clock in/out function

### ISSUE THREAD

**Issue by yamani** [mesilov/bitrix24-php-sdk#25]
is there any way to clock in/out employee using API

i looking to a way to integrate Bitrix with our Face/Finger print attendance system

**Comment by drumrock** [comment]
As far as I know, there is no such API function, but you can do something like adding a blog post to activity stream via log.blogpost.add:
http://dev.bitrixsoft.com/rest_help/log/log_blogpost_add.php

But... there is currently no "user logged in" or "clocked in" event to bind.

But there are events in tasks :-) You can automatically create tasks "Clock in" and "Clock out" for every user every day... and track changes via tasks events :-)

**Comment by yamani** [comment]
i was monitoring mysql tables and found the following SQL for Clock in/out/etc and tested the sql statements manually and found that they are functioning well 

i am adding them so someone may get benefit from them (do not forget to change values as needed)

Clock in for first time in the day:
INSERT INTO b_timeman_entries(`IP_OPEN`, `TIME_START`, `DATE_START`, `PAUSED`, `ACTIVE`, `MODIFIED_BY`, `USER_ID`) VALUES('127.0.0.1', '43737', '2015-11-27 12:08:57', 'N', 'Y', '1', '1')

Break at any time:
UPDATE b_timeman_entries SET `IP_CLOSE` = '127.0.0.1', `TIME_LEAKS` = 0, `TIME_FINISH` = 43739, `TIME_START` = 43737, `DATE_FINISH` = '2015-11-27 12:08:59', `DATE_START` = '2015-11-27 12:08:57', `PAUSED` = 'Y', `MODIFIED_BY` = 1, `USER_ID` = 1, `TIMESTAMP_X` = now() WHERE ID='5'
	
Continue after break or clock out:
UPDATE b_timeman_entries SET `TIME_LEAKS` = 0, `DURATION` = 0, `TIME_FINISH` = NULL, `TIME_START` = 43737, `DATE_FINISH` = NULL, `DATE_START` = '2015-11-27 12:08:57', `PAUSED` = 'N', `ACTIVE` = 'Y', `MODIFIED_BY` = 1, `TIMESTAMP_X` = now() WHERE ID='5'

clock out:
UPDATE b_timeman_entries SET `IP_CLOSE` = '127.0.0.1', `TIME_LEAKS` = 0, `DURATION` = 5, `TIME_FINISH` = 43742, `TIME_START` = 43737, `DATE_FINISH` = '2015-11-27 12:09:02', `DATE_START` = '2015-11-27 12:08:57', `PAUSED` = 'N', `MODIFIED_BY` = 1, `USER_ID` = 1, `TIMESTAMP_X` = now() WHERE ID='5'


find today's record for specific user so you decide to use insert if no result or update:
SELECT * FROM bsm_demo.b_timeman_entries  where user_id=1 and date_start>='2015-11-27'  and date_start<'2015-11-28';

the only tricky part that i still did not solve is the caching updates. after each sql of above you may need to refresh the cache to reflect the new status in the web pages. doing so from control panel is resolving the issue although not practical 

a lazy draft solution is to clear the following folders and table
C:\Bitrix\www\bitrix\managed_cache
C:\Bitrix\www\bitrix\cache
DELETE FROM b_cache_tag

thanks
