### ISSUE TITLE
Ошибка в деструкторе Response после обновления на alpha 6

### ISSUE THREAD

**Issue by SeventhSon77** [mesilov/bitrix24-php-sdk#277]
После обновления до 6 альфы стали падать все запросы к апи в деструкторе класса ответа на получении таймингов:

`Undefined index: namelookup_time_us at .../vendor/mesilov/bitrix24-php-sdk/src/Infrastructure/HttpClient/TransportLayer/NetworkTimingsParser.php:31`
(Ubuntu 18.04, php 7.4.27)
Откат до 5 альфы исправил ситуацию.

При этом, судя по логам, запросы нормально отрабатывают и возвращают респонзы от битрикса. 
На локальной машине (Arch, php 7.4.27)  проблем не возникало, воспроизвести проблему не удалось нигде кроме тестовой машины.

Запросы отправляю через метод `Core->call()`, `Core` собираю из `ApiClient` на базе `TraceableHttpClient`
Обработка ответа через `getResponseData()->getResult()->getResultData()`

**Comment by mesilov** [comment]
fixed in beta 1
