### ISSUE TITLE
Undefined index: namelookup_time_us

### ISSUE THREAD

**Issue by vladimirovii** [mesilov/bitrix24-php-sdk#307]
Ловлю вот такую ошибку 

Undefined index: namelookup_time_us in /<path_to>/vendor/mesilov/bitrix24-php-sdk/src/Infrastructure/HttpClient/TransportLayer/NetworkTimingsParser.php:31

php 7.4
2.0-alpha.6

**Comment by mesilov** [comment]
привет, а какая платформа?

попробуй переключиться на 7 ветку, там вроде пофиксили

https://github.com/mesilov/bitrix24-php-sdk/tree/273-alpha-7-pre-build
