### ISSUE TITLE
Custom timeout

### ISSUE THREAD

**Issue by damianoporta** [mesilov/bitrix24-php-sdk#34]
Hello
i am getting:

```
Operation timed out after 5001 milliseconds with 0 bytes received (cURL error code: 28)
```

I think we should implement a timeout setting to change its value if needed.

**Comment by mesilov** [comment]
[Implemented](https://github.com/mesilov/bitrix24-php-sdk/commit/f1b441bf46fe343fe2d21370eed7ddc1a333987b)
