### ISSUE TITLE
Add method im.message.add

### ISSUE THREAD

**Issue by geshan** [mesilov/bitrix24-php-sdk#35]
I could see this method exists by calling methods but there is no documentation about im.message.add.

Basically I want to add a message to private/public group chats. If you have any information on this please share. thanks.

**Comment by brusazorzo** [comment]
Same problem here.

**Comment by Steveb-p** [comment]
By messing around with my company Bitrix I managed to deduce parameters necessary for this command to be "properly" called.

From what I gather, you would need to call the `iBitrix24` instance (`$this->client`) with parameters like below.

```php
<?php
$fullResult = $this->client->call('im.message.add', [
  'user_id' => $userId,
  // Or, for group chat:
  // 'chat_id' => $chatId,
  'message' => $message,
]);
```

I think you can safely fork this SDK and insert similar method in im.php.

It should return message ID as a result. It did for me.

I haven't gotten further at this point, but it's sufficient for my purposes (calling webhook on specific events in another application). I don't need OAuth security for this nor the whole library, so I'll stick with calling my endpoint.

Hope this helps you and saves you some time.
