### ISSUE TITLE
Updating psr/log to version 2/3 was not included in 2.0-beta.1

### ISSUE THREAD

**Issue by MarkLukoshko** [mesilov/bitrix24-php-sdk#378]
Hello

Updating psr/log to version 2/3 was not included in 2.0-beta.1

Please update

https://github.com/mesilov/bitrix24-php-sdk/issues/245

**Comment by mesilov** [comment]
https://github.com/mesilov/bitrix24-php-sdk/pull/374/files

@MarkLukoshko try this branch
