### ISSUE TITLE
Стоит предусмотреть получение одноразовых токенов от онлайн событий?

### ISSUE THREAD

**Issue by badigit** [mesilov/bitrix24-php-sdk#387]
Сейчас можно эти токены передавать в  AccessToken::initFromArray 

Но   initFromArray будет пытаться достучаться до refreshToken (которого нет в онлайн событиях) и выдавать ошибки
Undefined array key "refresh_token"

В теории может быть рабочим подход в приложении "пробуем токен от события, если не сработало то токен приложения"

**Comment by mesilov** [comment]
`Сейчас можно эти токены передавать в AccessToken::initFromArray`

Приложи пожалуйста примеры структур данных

**Comment by mesilov** [comment]
https://github.com/mesilov/bitrix24-php-sdk/blob/385-publish-b24-php-sdk-beta-3/src/Core/Credentials/AccessToken.php#L92

implemented in beta-3
