### ISSUE TITLE
Increase ITEMS_PER_PAGE_LIMIT

### ISSUE THREAD

**Issue by kmligue** [mesilov/bitrix24-php-sdk#39]
I tried to overwrite the ITEMS_PER_PAGE_LIMIT in Bitrix24Entity class from 50 to 200. Looks like it's no effect. I called getList() method but it still returns 50 results. I just wanted to increase the maximum results.

**Comment by drumrock** [comment]
It's Bitrix24 API limit, not bitrix24-php-sdk.

**Comment by kmligue** [comment]
I see. Thanks!
