### ISSUE TITLE
Certain fields doesn't insert

### ISSUE THREAD

**Issue by vankaiser** [mesilov/bitrix24-php-sdk#59]
Hi, crm.lead.add doesn't allow me to insert phone, email, and IM, but other info are Ok.

**Comment by goodok21** [comment]
IM - array

    private function createContact($inputData)
    {
        $addData = array();
        $addData['NAME'] = $inputData['NAME'];
        $addData['SECOND_NAME'] = $inputData['SECOND_NAME'];
        $addData['LAST_NAME'] = $inputData['LAST_NAME'];
        $addData['IM'] = array($inputData['IM']);
        $params = array();

        $contact = new Contact($this->bx24);

        $result = $contact->add($addData, $params);

        if(empty($result['result'])) {
            throw new \RuntimeException("Failed to contact create");
            print_r('error: '.$result);
        }

        $contactId = $result['result'];

        return $contactId;
    }

**Comment by ronalddas** [comment]
@vankaiser  I am trying to use the crm.lead.add, am always getting the error
`The required field 'Lead Name' is missing.<br />`. I Checked necessary fields using the crm.lead.fields, and only "TITLE" has isRequired:True, even if i include TITLE, am getting the same error. 
Did you face this bug?

**Comment by vankaiser** [comment]
Have you tried to pass the name param as empty string? Name might be required.
