### ISSUE TITLE
Fatal error: Interface 'Bitrix24\Contracts\iBitrix24' not found 

### ISSUE THREAD

**Issue by okkie-nel** [mesilov/bitrix24-php-sdk#75]
I get this fatal error installed with composer

Fatal error: Interface 'Bitrix24\Contracts\iBitrix24' not found in bitrix24.php on line 36.

its probably something stupid i am missing

**Comment by krunalp1993** [comment]
You should install this using composer, 

Example
composer require mesilov/bitrix24-php-sdk
- Which will add all dependencies in vendor folder and you can include autoload.php file to use this.
